# Generated by Django 5.2.13 on 2026-04-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_about_socialmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
