# Generated by Django 5.2.13 on 2026-04-21 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': 'Social Media'},
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='url',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(default='Facebook', max_length=100),
        ),
    ]
